spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:qwerty123}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/

jwt:
  secret: u6rckmOPVwT9OuoWZf9lZtabfM6TTRGTYiS6OQ4Nkb8=   # tu clave en Base64
  expirationMs: 3600000                        # tiempo en milisegundos (ej. 1 hora)

logging:
  level:
    org.springframework.security: DEBUG
