version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Puerto para las conexiones AMQP
      - "15672:15672"  # Puerto para la consola web de administración
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq-net
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  rabbitmq-net:
    driver: bridge
