server:
  port: 8085

spring:
  application:
    name: ms-autenticacion
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: qwerty123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
# ? Clave secreta para firmar los tokens JWT
jwt:
  secret: una_clave_secreta_muy_larga_y_segura_para_HS512_con_al_menos_32_bytes!

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

