spring:
  web:
    resources:
      static-locations: [ ]
  application:
    name: SERVICIO-PUBLICACIONES
  datasource:
    url: jdbc:postgresql://localhost:5432/db-publications
    username: postgres
    password: qwerty123
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*" # Puedes reemplazar por health,info,metrics en producción
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

info:
  app:
    name: "Servicio Publicaciones"
    version: "1.0.0"
    author: "Desarrollador"